name: Trigger auto deployment for integration-n8n

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/integration-n8n-AutoDeployTrigger-6a41985c-7010-4659-9ac0-fa7c160f9a0d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.INTEGRATIONN8N_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INTEGRATIONN8N_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INTEGRATIONN8N_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.INTEGRATIONN8N_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INTEGRATIONN8N_REGISTRY_PASSWORD }}
          containerAppName: integration-n8n
          resourceGroup: AMED-BizOps-CentralUS-RG-A1DataUtilities-JS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


